Controller and route added for profile&availability #6
hatchways/team-samosa pull request #46
Opened 2021-10-18 04:55 UTC by JAFAJ0

### What this PR does (required):
- list PR functionality here
- Profile
- get(by userId)
- post(see userId, phone number, email)
- update
Availability
- get( a list with id)
- post( Cannot overlap time with the same id)
- update(get by availabilityId, Cannot overlap time with the same id)

### Any information needed to test this feature (required):
- Use tools like postsql

2021-10-18 09:33 UTC, ezeilo-su requested changes
What a neat code :+1: 
Just check out the few comments below and fix them.
Happy coding!

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +// @access Private
Good docummentation

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +// @access Private
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +    }
A good security practice

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +        res.status(400);
Correct status code

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +        res.status(400);
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +// @access Private
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +    res.status(200).json(availability);
Nice one!

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +// @access Private
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +// @access Private
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +    const { firstName, lastName, email, phoneNum } = req.body;
You can first validate all these fields and return a bad request status if any of them is required but missing in the request body.

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +    }
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +    }
I think this should come first

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +// @access Private
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +exports.updateProfile = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +exports.createProfile = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Profile.js
> +exports.getProfile = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +exports.updateAvailability = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +exports.getAvailability = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/controllers/Availability.js
> +exports.createAvailability = asyncHandler(async (req, res, next) => {
You can remove `next` if not used

2021-10-18 09:33 UTC, ezeilo-su commented on server/models/Availablity.js
> +    }
:+1:

2021-10-18 09:33 UTC, ezeilo-su commented on server/models/Profile.js
> +    },
:+1:

2021-10-20 00:47 UTC, rajivtitus commented on server/controllers/Availability.js
> +        $or: [{ userId: userId }]
```suggestion
         userId
```

I don't think we need an $or condition as we are only searching for the 'userId' field :)

2021-10-20 00:50 UTC, rajivtitus commented on server/controllers/Availability.js
> +    const availability = await Availability.findById(availabilityId);
Optional: Only the profile owner should be allowed to update their availability. The way we currently have it setup, any user can modify any other user's availability :)

2021-10-20 00:51 UTC, rajivtitus commented on server/controllers/Profile.js
> +    const { profileupdates } = req.body;
```suggestion
    const { profileUpdates } = req.body;

```

camelCase :)

2021-10-20 00:51 UTC, rajivtitus commented on server/controllers/Profile.js
> +    profile.status = profileupdates;
```suggestion
    profile.status = profileUpdates;

```

2021-10-20 00:53 UTC, rajivtitus commented on server/routes/Profile.js
> +router.route("/:id").patch(protect, updateProfile);
```suggestion
router.route("/").patch(protect, updateProfile);

```

I don't see the path params being using in the 'updateProfile' controller

2021-10-20 00:54 UTC, rajivtitus approved these changes
Good work with this! Just some minor suggestions, please address them before merging. Thanks!

2021-10-20 01:49 UTC, merged