Merge profile pages
hatchways/team-samosa pull request #70
Opened 2021-11-02 05:55 UTC by JAFAJ0

### What this PR does (required):
- This PR combine and simplify the complex profile page which is because of merge and separate tasks

### Screenshots / Videos (front-end only):
- 
![ep](https://user-images.githubusercontent.com/86894074/139793644-8f74ecfe-8a13-4085-9876-2b233e1c4037.png)

### Any information needed to test this feature (required):
- THIS PR SHOULD BE PROVED AFTER PROFILE PHOTO IS APPROVED AND MERGED

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-11-02 10:28 UTC, ezeilo-su requested changes
A lot of progress here. Please can you link your ticket to this PR? Follow this [guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Also, resolve the merge conflict before another review.

2021-11-02 10:28 UTC, ezeilo-su commented on client/src/pages/ProfileSkeleton/Profile.tsx
> +    // loading for a split seconds until history.push works
Let's remove the comment

2021-11-02 10:28 UTC, ezeilo-su commented on server/controllers/profilephoto.js
> +            console.log(data)
Please remove comment

2021-11-04 21:23 UTC, JAFAJ0 commented on client/src/components/Bookings/BookingsSideBanner/BookingsSideBanner.tsx
> +      <Grid item>{requests.length > 1 && <BookingsPaper requests={requests} />}</Grid>
Not my part of code and come in by merge issue

2021-11-05 02:51 UTC, merged